import 'package:flutter/material.dart';
import '../core/network/api_client.dart';
import '../features/chats/chat_repository.dart';
import '../features/profile/profile_repository.dart';

class HomeShell extends StatefulWidget{final ApiClient api;final VoidCallback onLogout;const HomeShell({super.key,required this.api,required this.onLogout});@override State<HomeShell> createState()=>_HomeShellState();}
class _HomeShellState extends State<HomeShell>{int index=0;@override Widget build(BuildContext c){final pages=[_Chats(api:widget.api),const _Page(title:'Discover',icon:Icons.explore,text:'Find people, creators, businesses and public communities.'),const _Page(title:'Communities',icon:Icons.groups,text:'Join communities and channels that match your interests.'),const _Page(title:'Calls',icon:Icons.call,text:'Voice and video calling infrastructure is ready for integration.'),_Profile(api:widget.api,onLogout:widget.onLogout)];return Scaffold(body:pages[index],bottomNavigationBar:NavigationBar(selectedIndex:index,onDestinationSelected:(v)=>setState(()=>index=v),destinations:const[NavigationDestination(icon:Icon(Icons.chat_bubble_outline),selectedIcon:Icon(Icons.chat_bubble),label:'Chats'),NavigationDestination(icon:Icon(Icons.explore_outlined),selectedIcon:Icon(Icons.explore),label:'Discover'),NavigationDestination(icon:Icon(Icons.groups_outlined),selectedIcon:Icon(Icons.groups),label:'Communities'),NavigationDestination(icon:Icon(Icons.call_outlined),selectedIcon:Icon(Icons.call),label:'Calls'),NavigationDestination(icon:Icon(Icons.person_outline),selectedIcon:Icon(Icons.person),label:'Profile')]));}}
class _Chats extends StatelessWidget{final ApiClient api;const _Chats({required this.api});@override Widget build(BuildContext c){final repo=ChatRepository(api);return SafeArea(child:FutureBuilder(future:repo.rooms(),builder:(c,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(s.hasError)return Center(child:Text('Could not load chats\n${s.error}'));final rooms=s.data??[];return CustomScrollView(slivers:[SliverAppBar(title:const Text('Chats'),floating:true,actions:[IconButton(onPressed:(){},icon:const Icon(Icons.search))]),if(rooms.isEmpty)const SliverFillRemaining(child:Center(child:Text('No conversations yet'))),SliverList.builder(itemCount:rooms.length,itemBuilder:(c,i)=>ListTile(leading:const CircleAvatar(child:Icon(Icons.person)),title:Text(rooms[i].title??'Conversation'),subtitle:const Text('Start a conversation'),onTap:(){})]);})));}}
class _Profile extends StatelessWidget{final ApiClient api;final VoidCallback onLogout;const _Profile({required this.api,required this.onLogout});@override Widget build(BuildContext c){final repo=ProfileRepository(api);return SafeArea(child:FutureBuilder(future:repo.me(),builder:(c,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());final p=s.data??{};return ListView(padding:const EdgeInsets.all(24),children:[const Text('Profile',style:TextStyle(fontSize:32,fontWeight:FontWeight.w800)),const SizedBox(height:24),CircleAvatar(radius:44,child:Text((p['display_name']??'?').toString().substring(0,1).toUpperCase())),const SizedBox(height:16),Text(p['display_name']??'',style:Theme.of(c).textTheme.headlineSmall),Text('@${p['username']??''}'),if((p['bio']??'').toString().isNotEmpty)Padding(padding:const EdgeInsets.only(top:8),child:Text(p['bio'])),const SizedBox(height:32),ListTile(leading:const Icon(Icons.lock_outline),title:const Text('Privacy & security')),ListTile(leading:const Icon(Icons.account_balance_wallet_outlined),title:const Text('Wallet'),subtitle:const Text('Payments, creator earnings and gifts')),ListTile(leading:const Icon(Icons.settings_outlined),title:const Text('Settings')),const SizedBox(height:16),OutlinedButton(onPressed:onLogout,child:const Text('Sign out'))]);}));}}
class _Page extends StatelessWidget{final String title,text;final IconData icon;const _Page({required this.title,required this.icon,required this.text});@override Widget build(BuildContext c)=>SafeArea(child:Center(child:Padding(padding:const EdgeInsets.all(32),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(icon,size:72),const SizedBox(height:20),Text(title,style:Theme.of(c).textTheme.headlineMedium),const SizedBox(height:10),Text(text,textAlign:TextAlign.center)])));}
